[project]
name = "my-lib"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dtorannpu", email = "dtorannpu@gmail.com" }
]
requires-python = ">=3.13, <4"
dependencies = []

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
